[versions]
activityCompose = "1.12.2"
agp = "8.9.3"
commonsdk = "1.0.7"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
compileSdk = "36"
compileSdkVersion = "android-36"
minSdk = "24"
targetSdk = "36"
dokka = "2.1.0"
ktlint = "14.0.1"
detekt = "1.23.8"
mockito = "5.21.0"
konsistVersion = "0.17.3"
userbehaviorsdk = "1.0.0"
kotlinGradlePlugin = "2.1.0"
composeBom = "2025.12.01"
lifecycleRuntimeCompose = "2.10.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
commonsdk = { module = "com.github.adhamkhwaldeh.WeatherSdk:CommonSDK", version.ref = "commonsdk" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsistVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
userbehaviorsdk = { module = "com.github.adhamkhwaldeh:UserBehaviorSDK", version.ref = "userbehaviorsdk" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }

# Compose and Lifecycle dependencies
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
